[project]
name = "upscale-detector"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "matplotlib>=3.10.7",
    "opencv-python>=4.12.0.88",
    "scikit-image>=0.25.2",
    "tqdm>=4.67.1",
]
